# requirements: git bash make python3-pip python3-venv
SHELL := /bin/bash

.PHONY: clean # clean files generated by automated tasks
clean:
	rm -rf awesome-sysadmin/ awesome-sysadmin-html/ html/

.PHONY: install # install build tools in a virtualenv
install:
	python3 -m venv .venv
	source .venv/bin/activate && \
	pip3 install wheel && \
	pip3 install --force git+https://github.com/nodiscc/hecat.git@1.6.0

.PHONY: import # import data from the original list at https://github.com/awesome-selfhosted/awesome-selfhosted
import: clean install
	git clone --depth=1 https://github.com/awesome-foss/awesome-sysadmin/
	cp awesome-sysadmin/AUTHORS AUTHORS
	rm -rf tags/ software/ platforms/
	mkdir -p tags/ software/ platforms/
	source .venv/bin/activate && \
	hecat --config .hecat/import.yml
