name: Environment Modules
website_url: https://envmodules.io/
description: Environment Modules provides for the dynamic modification of a user's environment via modulefiles.
licenses:
  - GPL-2.0
platforms:
  - Tcl
tags:
  - Build and software organization tools
source_code_url: https://github.com/envmodules/modules
stargazers_count: 848
updated_at: '2026-05-18'
archived: false
current_release:
  tag: v5.6.1
  published_at: '2025-11-25'
commit_history:
  2026-03: 2
  2026-04: 0
  2026-05: 8
