name: rConfig
website_url: https://www.rconfig.com/
description: Network device configuration management tool.
licenses:
  - GPL-3.0
platforms:
  - PHP
tags:
  - Network Configuration Management
source_code_url: https://github.com/rconfig/rconfig
stargazers_count: 180
updated_at: '2026-05-07'
archived: false
commit_history:
  2026-03: 5
  2026-04: 11
  2026-05: 12
