name: import

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

env:
  GTIHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  import:
    if: github.repository == 'Rabenherz112/awesome-sysadmin-data'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - run: make install
      - run: make import
      - name: commit and push changes
        run: |
          git config user.name awesome-sysadmin-bot
          git config user.email github-actions@github.com
          git add software/ tags/ licenses*.yml
          git diff-index --quiet HEAD || git commit -m "[bot] import projects"
          git push
