name: import.yml

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

env:
  GTIHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  import:
    if: github.repository == 'Rabenherz112/awesome-sysadmin-data'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - run: make install
      - run: make import
